-- Tasks are faster than snowpipes when using integration with gcp 

CREATE OR REPLACE TABLE CS_TEST.PUBLIC.TEST_RAW_DATA_TABLE_TASK
(JSON_DATA VARIANT);

CREATE OR REPLACE TASK GCS_SNOWFLAKE_TASK
    WAREHOUSE = 'COMPUTE_WH'
    SCHEDULE = '1 MINUTE'
    AS
        COPY INTO CS_TEST.PUBLIC.TEST_RAW_DATA_TABLE_TASK
        FROM @CS_TEST.PUBLIC.GCP_EXT_STAGE
            FILE_FORMAT = CS_TEST.FILE_FORMATS.JSON_FORMAT;

-- By default a task is suspended when created and hence resume the task
ALTER TASK GCS_SNOWFLAKE_TASK RESUME;

-- To suspend task
ALTER TASK GCS_SNOWFLAKE_TASK SUSPEND;


SELECT * FROM CS_TEST.PUBLIC.TEST_RAW_DATA_TABLE_TASK;