CREATE OR REPLACE STORAGE INTEGRATION CS_REAL_TIME_DATA
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = GCS
    ENABLED = TRUE
    STORAGE_ALLOWED_LOCATIONS = ('gcs://pb-gcp-snow-bucket-real/click-stream');

CREATE OR REPLACE STAGE GCP_EXT_STAGE
    URL = 'gcs://pb-gcp-snow-bucket-real/click-stream'
    STORAGE_INTEGRATION = CS_REAL_TIME_DATA;

DESC INTEGRATION CS_REAL_TIME_DATA;

LIST @CS_TEST.PUBLIC.GCP_EXT_STAGE;

CREATE OR REPLACE SCHEMA CS_TEST.FILE_FORMATS;

CREATE OR REPLACE FILE FORMAT CS_TEST.FILE_FORMATS.JSON_FORMAT
    TYPE = JSON;


CREATE OR REPLACE TABLE CS_TEST.PUBLIC.TEST_RAW_DATA_TABLE
(JSON_DATA VARIANT);


SELECT * FROM CS_TEST.PUBLIC.TEST_RAW_DATA_TABLE;

CREATE OR REPLACE SCHEMA CS_TEST.SOWPIPES;




